server:
  port: 48081

--- #################### æ•°æ®åº“ç›¸å…³é…ç½® ####################
spring:
  autoconfigure:
    # noinspection SpringBootApplicationYaml
    exclude:
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration # é»˜è®¤ local ç¯å¢ƒï¼Œä¸å¼€å¯ Quartz çš„è‡ªåŠ¨é…ç½®
      - org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration # ç¦ç”¨ AI æ¨¡å—çš„ Qdrantï¼Œæ‰‹åŠ¨åˆ›å»º
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration # ç¦ç”¨ AI æ¨¡å—çš„ Milvusï¼Œæ‰‹åŠ¨åˆ›å»º
  # æ•°æ®æºé…ç½®é¡¹
  datasource:
    druid: # Druid ã€ç›‘æ§ã€‘ç›¸å…³çš„å…¨å±€é…ç½®
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # è®¾ç½®ç™½åå•ï¼Œä¸å¡«åˆ™å…è®¸æ‰€æœ‰è®¿é—®
        url-pattern: /druid/*
        login-username: # æ§åˆ¶å°ç®¡ç†ç”¨æˆ·åå’Œå¯†ç 
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true # æ…¢ SQL è®°å½•
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # å¤šæ•°æ®æºé…ç½®
      druid: # Druid ã€è¿æ¥æ± ã€‘ç›¸å…³çš„å…¨å±€é…ç½®
        initial-size: 1 # åˆå§‹è¿æ¥æ•°
        min-idle: 1 # æœ€å°è¿æ¥æ± æ•°é‡
        max-active: 20 # æœ€å¤§è¿æ¥æ± æ•°é‡
        max-wait: 60000 # é…ç½®è·å–è¿æ¥ç­‰å¾…è¶…æ—¶çš„æ—¶é—´ï¼Œå•ä½ï¼šæ¯«ç§’ï¼ˆ1 åˆ†é’Ÿï¼‰
        time-between-eviction-runs-millis: 60000 # é…ç½®é—´éš”å¤šä¹…æ‰è¿›è¡Œä¸€æ¬¡æ£€æµ‹ï¼Œæ£€æµ‹éœ€è¦å…³é—­çš„ç©ºé—²è¿æ¥ï¼Œå•ä½ï¼šæ¯«ç§’ï¼ˆ1 åˆ†é’Ÿï¼‰
        min-evictable-idle-time-millis: 600000 # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å°ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½ï¼šæ¯«ç§’ï¼ˆ10 åˆ†é’Ÿï¼‰
        max-evictable-idle-time-millis: 1800000 # é…ç½®ä¸€ä¸ªè¿æ¥åœ¨æ± ä¸­æœ€å¤§ç”Ÿå­˜çš„æ—¶é—´ï¼Œå•ä½ï¼šæ¯«ç§’ï¼ˆ30 åˆ†é’Ÿï¼‰
        validation-query: SELECT 1 FROM DUAL # é…ç½®æ£€æµ‹è¿æ¥æ˜¯å¦æœ‰æ•ˆ
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true # æ˜¯å¦å¼€å¯ PreparedStatement ç¼“å­˜
        max-pool-prepared-statement-per-connection-size: 20 # æ¯ä¸ªè¿æ¥ç¼“å­˜çš„ PreparedStatement æ•°é‡
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true # MySQL Connector/J 8.X è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true # MySQL Connector/J 5.X è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:postgresql://127.0.0.1:5432/ruoyi-vue-pro # PostgreSQL è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:oracle:thin:@127.0.0.1:1521:xe # Oracle è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=ruoyi-vue-pro;SelectMethod=cursor;encrypt=false;rewriteBatchedStatements=true;useUnicode=true;characterEncoding=utf-8 # SQLServer è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:dm://127.0.0.1:5236?schema=RUOYI_VUE_PRO # DM è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:kingbase8://127.0.0.1:54321/test  # äººå¤§é‡‘ä»“ KingbaseES è¿æ¥çš„ç¤ºä¾‹
          #          url: jdbc:postgresql://127.0.0.1:5432/postgres # OpenGauss è¿æ¥çš„ç¤ºä¾‹
          username: root
          password: 
          #          username: sa # SQL Server è¿æ¥çš„ç¤ºä¾‹
          #          password: Yudao@2024 # SQL Server è¿æ¥çš„ç¤ºä¾‹
          #          username: SYSDBA # DM è¿æ¥çš„ç¤ºä¾‹
          #          password: SYSDBA001 # DM è¿æ¥çš„ç¤ºä¾‹
          #          username: root # OpenGauss è¿æ¥çš„ç¤ºä¾‹
          #          password: Yudao@2024 # OpenGauss è¿æ¥çš„ç¤ºä¾‹
        slave: # æ¨¡æ‹Ÿä»åº“ï¼Œå¯æ ¹æ®è‡ªå·±éœ€è¦ä¿®æ”¹
          lazy: true # å¼€å¯æ‡’åŠ è½½ï¼Œä¿è¯å¯åŠ¨é€Ÿåº¦
          url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
          username: root
          password:
#        tdengine: # IoT æ•°æ®åº“ï¼ˆéœ€è¦ IoT ç‰©è”ç½‘å†å¼€å¯å™¢ï¼ï¼‰
#          url: jdbc:TAOS-RS://127.0.0.1:6041/ruoyi_vue_pro
#          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
#          username: root
#          password: taosdata
#          druid:
#            validation-query: SELECT SERVER_STATUS() # TDengine æ•°æ®æºçš„æœ‰æ•ˆæ€§æ£€æŸ¥ SQL

  # Redis é…ç½®ã€‚Redisson é»˜è®¤çš„é…ç½®è¶³å¤Ÿä½¿ç”¨ï¼Œä¸€èˆ¬ä¸éœ€è¦è¿›è¡Œè°ƒä¼˜
  data:
    redis:
      host: 127.0.0.1 # åœ°å€
      port: 6379 # ç«¯å£
      database: 0 # æ•°æ®åº“ç´¢å¼•
  #    password: dev # å¯†ç ï¼Œå»ºè®®ç”Ÿäº§ç¯å¢ƒå¼€å¯

--- #################### å®šæ—¶ä»»åŠ¡ç›¸å…³é…ç½® ####################

# Quartz é…ç½®é¡¹ï¼Œå¯¹åº” QuartzProperties é…ç½®ç±»
spring:
  quartz:
    auto-startup: true # æœ¬åœ°å¼€å‘ç¯å¢ƒï¼Œå°½é‡ä¸è¦å¼€å¯ Job
    scheduler-name: schedulerName # Scheduler åå­—ã€‚é»˜è®¤ä¸º schedulerName
    job-store-type: jdbc # Job å­˜å‚¨å™¨ç±»å‹ã€‚é»˜è®¤ä¸º memory è¡¨ç¤ºå†…å­˜ï¼Œå¯é€‰ jdbc ä½¿ç”¨æ•°æ®åº“ã€‚
    wait-for-jobs-to-complete-on-shutdown: true # åº”ç”¨å…³é—­æ—¶ï¼Œæ˜¯å¦ç­‰å¾…å®šæ—¶ä»»åŠ¡æ‰§è¡Œå®Œæˆã€‚é»˜è®¤ä¸º false ï¼Œå»ºè®®è®¾ç½®ä¸º true
    properties: # æ·»åŠ  Quartz Scheduler é™„åŠ å±æ€§ï¼Œæ›´å¤šå¯ä»¥çœ‹ http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html æ–‡æ¡£
      org:
        quartz:
          # Scheduler ç›¸å…³é…ç½®
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO # è‡ªåŠ¨ç”Ÿæˆ instance ID
          # JobStore ç›¸å…³é…ç½®
          jobStore:
            # JobStore å®ç°ç±»ã€‚å¯è§åšå®¢ï¼šhttps://blog.csdn.net/weixin_42458219/article/details/122247162
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true # æ˜¯é›†ç¾¤æ¨¡å¼
            clusterCheckinInterval: 15000 # é›†ç¾¤æ£€æŸ¥é¢‘ç‡ï¼Œå•ä½ï¼šæ¯«ç§’ã€‚é»˜è®¤ä¸º 15000ï¼Œå³ 15 ç§’
            misfireThreshold: 60000 # misfire é˜€å€¼ï¼Œå•ä½ï¼šæ¯«ç§’ã€‚
          # çº¿ç¨‹æ± ç›¸å…³é…ç½®
          threadPool:
            threadCount: 25 # çº¿ç¨‹æ± å¤§å°ã€‚é»˜è®¤ä¸º 10 ã€‚
            threadPriority: 5 # çº¿ç¨‹ä¼˜å…ˆçº§
            class: org.quartz.simpl.SimpleThreadPool # çº¿ç¨‹æ± ç±»å‹
    jdbc: # ä½¿ç”¨ JDBC çš„ JobStore çš„æ—¶å€™ï¼ŒJDBC çš„é…ç½®
      initialize-schema: NEVER # æ˜¯å¦è‡ªåŠ¨ä½¿ç”¨ SQL åˆå§‹åŒ– Quartz è¡¨ç»“æ„ã€‚è¿™é‡Œè®¾ç½®æˆ never ï¼Œæˆ‘ä»¬æ‰‹åŠ¨åˆ›å»ºè¡¨ç»“æ„ã€‚

--- #################### æ¶ˆæ¯é˜Ÿåˆ—ç›¸å…³ ####################

# rocketmq é…ç½®é¡¹ï¼Œå¯¹åº” RocketMQProperties é…ç½®ç±»
rocketmq:
  name-server: 127.0.0.1:9876 # RocketMQ Namesrv

spring:
  # RabbitMQ é…ç½®é¡¹ï¼Œå¯¹åº” RabbitProperties é…ç½®ç±»
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ æœåŠ¡çš„åœ°å€
    port: 5672 # RabbitMQ æœåŠ¡çš„ç«¯å£
    username: rabbit # RabbitMQ æœåŠ¡çš„è´¦å·
    password: rabbit # RabbitMQ æœåŠ¡çš„å¯†ç 
  # Kafka é…ç½®é¡¹ï¼Œå¯¹åº” KafkaProperties é…ç½®ç±»
  kafka:
    bootstrap-servers: 127.0.0.1:9092 # æŒ‡å®š Kafka Broker åœ°å€ï¼Œå¯ä»¥è®¾ç½®å¤šä¸ªï¼Œä»¥é€—å·åˆ†éš”

--- #################### æœåŠ¡ä¿éšœç›¸å…³é…ç½® ####################

# Lock4j é…ç½®é¡¹
lock4j:
  acquire-timeout: 3000 # è·å–åˆ†å¸ƒå¼é”è¶…æ—¶æ—¶é—´ï¼Œé»˜è®¤ä¸º 3000 æ¯«ç§’
  expire: 30000 # åˆ†å¸ƒå¼é”çš„è¶…æ—¶æ—¶é—´ï¼Œé»˜è®¤ä¸º 30 æ¯«ç§’

--- #################### ç›‘æ§ç›¸å…³é…ç½® ####################

# Actuator ç›‘æ§ç«¯ç‚¹çš„é…ç½®é¡¹
management:
  endpoints:
    web:
      base-path: /actuator # Actuator æä¾›çš„ API æ¥å£çš„æ ¹ç›®å½•ã€‚é»˜è®¤ä¸º /actuator
      exposure:
        include: '*' # éœ€è¦å¼€æ”¾çš„ç«¯ç‚¹ã€‚é»˜è®¤å€¼åªæ‰“å¼€ health å’Œ info ä¸¤ä¸ªç«¯ç‚¹ã€‚é€šè¿‡è®¾ç½® * ï¼Œå¯ä»¥å¼€æ”¾æ‰€æœ‰ç«¯ç‚¹ã€‚

# Spring Boot Admin é…ç½®é¡¹
spring:
  boot:
    admin:
      # Spring Boot Admin Client å®¢æˆ·ç«¯çš„ç›¸å…³é…ç½®
      client:
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path} # è®¾ç½® Spring Boot Admin Server åœ°å€
        instance:
          service-host-type: IP # æ³¨å†Œå®ä¾‹æ—¶ï¼Œä¼˜å…ˆä½¿ç”¨ IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
      # Spring Boot Admin Server æœåŠ¡ç«¯çš„ç›¸å…³é…ç½®
      context-path: /admin # é…ç½® Spring

# æ—¥å¿—æ–‡ä»¶é…ç½®
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # æ—¥å¿—æ–‡ä»¶åï¼Œå…¨è·¯å¾„
  level:
    # é…ç½®è‡ªå·±å†™çš„ MyBatis Mapper æ‰“å°æ—¥å¿—
    cn.iocoder.yudao.module.bpm.dal.mysql: debug
    cn.iocoder.yudao.module.infra.dal.mysql: debug
    cn.iocoder.yudao.module.infra.dal.mysql.logger.ApiErrorLogMapper: INFO # é…ç½® ApiErrorLogMapper çš„æ—¥å¿—çº§åˆ«ä¸º infoï¼Œé¿å…å’Œ GlobalExceptionHandler é‡å¤æ‰“å°
    cn.iocoder.yudao.module.infra.dal.mysql.job.JobLogMapper: INFO # é…ç½® JobLogMapper çš„æ—¥å¿—çº§åˆ«ä¸º info
    cn.iocoder.yudao.module.infra.dal.mysql.file.FileConfigMapper: INFO # é…ç½® FileConfigMapper çš„æ—¥å¿—çº§åˆ«ä¸º info
    cn.iocoder.yudao.module.pay.dal.mysql: debug
    cn.iocoder.yudao.module.pay.dal.mysql.notify.PayNotifyTaskMapper: INFO # é…ç½® PayNotifyTaskMapper çš„æ—¥å¿—çº§åˆ«ä¸º info
    cn.iocoder.yudao.module.system.dal.mysql: debug
    cn.iocoder.yudao.module.system.dal.mysql.sms.SmsChannelMapper: INFO # é…ç½® SmsChannelMapper çš„æ—¥å¿—çº§åˆ«ä¸º info
    cn.iocoder.yudao.module.tool.dal.mysql: debug
    cn.iocoder.yudao.module.member.dal.mysql: debug
    cn.iocoder.yudao.module.trade.dal.mysql: debug
    cn.iocoder.yudao.module.promotion.dal.mysql: debug
    cn.iocoder.yudao.module.statistics.dal.mysql: debug
    cn.iocoder.yudao.module.crm.dal.mysql: debug
    cn.iocoder.yudao.module.erp.dal.mysql: debug
    cn.iocoder.yudao.module.iot.dal.mysql: debug
    cn.iocoder.yudao.module.iot.dal.tdengine: DEBUG
    cn.iocoder.yudao.module.ai.dal.mysql: debug
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR # TODO èŠ‹è‰¿ï¼šå…ˆç¦ç”¨ï¼ŒSpring Boot 3.X å­˜åœ¨éƒ¨åˆ†é”™è¯¯çš„ WARN æç¤º

debug: false

--- #################### å¾®ä¿¡å…¬ä¼—å·ã€å°ç¨‹åºç›¸å…³é…ç½® ####################
wx:
  mp: # å…¬ä¼—å·é…ç½®ï¼ˆå¿…å¡«ï¼‰ï¼Œå‚è§ https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-mp-spring-boot-starter/README.md æ–‡æ¡£
#    app-id: wx041349c6f39b268b # æµ‹è¯•å·ï¼ˆç‰›å¸Œå°§æä¾›çš„ï¼‰
#    secret: 5abee519483bc9f8cb37ce280e814bd0
#    app-id: wx5b23ba7a5589ecbb # æµ‹è¯•å·ï¼ˆè‡ªå·±çš„ï¼‰
#    secret: 2a7b3b20c537e52e74afd395eb85f61f
    app-id: wxf56b1542b9e85f8a # æµ‹è¯•å·ï¼ˆKongdy æä¾›çš„ï¼‰
    secret: 496379dcef1ba869e9234de8d598cfd3
    # å­˜å‚¨é…ç½®ï¼Œè§£å†³ AccessToken çš„è·¨èŠ‚ç‚¹çš„å…±äº«
    config-storage:
      type: RedisTemplate # é‡‡ç”¨ RedisTemplate æ“ä½œ Redisï¼Œä¼šè‡ªåŠ¨ä» Spring ä¸­è·å–
      key-prefix: wx # Redis Key çš„å‰ç¼€
      http-client-type: HttpClient # é‡‡ç”¨ HttpClient è¯·æ±‚å¾®ä¿¡å…¬ä¼—å·å¹³å°
  miniapp: # å°ç¨‹åºé…ç½®ï¼ˆå¿…å¡«ï¼‰ï¼Œå‚è§ https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/README.md æ–‡æ¡£
    #    appid: wx62056c0d5e8db250 # æµ‹è¯•å·ï¼ˆç‰›å¸Œå°§æä¾›çš„ï¼‰
    #    secret: 333ae72f41552af1e998fe1f54e1584a
#    appid: wx63c280fe3248a3e7 # wenhualiançš„æ¥å£æµ‹è¯•å·
#    secret: 6f270509224a7ae1296bbf1c8cb97aed
    appid: wxc4598c446f8a9cb3 # æµ‹è¯•å·ï¼ˆKongdy æä¾›çš„ï¼‰
    secret: 4a1a04e07f6a4a0751b39c3064a92c8b
#    appid: wx66186af0759f47c9 # æµ‹è¯•å·ï¼ˆpuhui æä¾›çš„ï¼‰
#    secret: 3218bcbd112cbc614c7264ceb20144ac
    config-storage:
      type: RedisTemplate # é‡‡ç”¨ RedisTemplate æ“ä½œ Redisï¼Œä¼šè‡ªåŠ¨ä» Spring ä¸­è·å–
      key-prefix: wa # Redis Key çš„å‰ç¼€
      http-client-type: HttpClient # é‡‡ç”¨ HttpClient è¯·æ±‚å¾®ä¿¡å…¬ä¼—å·å¹³å°

--- #################### èŠ‹é“ç›¸å…³é…ç½® ####################

# èŠ‹é“é…ç½®é¡¹ï¼Œè®¾ç½®å½“å‰é¡¹ç›®æ‰€æœ‰è‡ªå®šä¹‰çš„é…ç½®
yudao:
  captcha:
    enable: false # æœ¬åœ°ç¯å¢ƒï¼Œæš‚æ—¶å…³é—­å›¾ç‰‡éªŒè¯ç ï¼Œæ–¹ä¾¿ç™»å½•ç­‰æ¥å£çš„æµ‹è¯•ï¼›
  security:
    mock-enable: true
    permit-all-urls:
      - /admin-api/test/notification/**       # ğŸ”§ ä¸´æ—¶é€šçŸ¥ç³»ç»Ÿæµ‹è¯•è·¯å¾„
      - /admin-api/infra/notification/**      # ğŸ”§ é€šçŸ¥ç³»ç»Ÿæ‰€æœ‰æ¥å£ï¼ˆä¿®å¤è·¯å¾„å†²çªï¼‰
      - /admin-api/infra/messages/**          # ğŸ”§ ä¿ç•™æµ‹è¯•Controllerè·¯å¾„
      - /admin-api/infra/test/**              # ğŸ”§ infraæ¨¡å—æµ‹è¯•æ¥å£
      - /admin-api/infra/server-test/**       # ğŸ”§ serveræ¨¡å—æµ‹è¯•Controllerï¼ˆadmin-apiè·¯å¾„ï¼‰
      - /admin-api/system/notification-test/**
      - /admin-api/mock-school/**             # Mock School APIæ¥å£
      - /admin-api/server/notification/**     # ä¿ç•™å¤‡ç”¨

--- #################### Mock School API é›†æˆé…ç½® ####################
# Mock School API é…ç½®
mock:
  school-api:
    base-url: http://localhost:48082
    enabled: true
    # è¿æ¥è¶…æ—¶æ—¶é—´ï¼ˆç§’ï¼‰
    connect-timeout: 5
    # è¯»å–è¶…æ—¶æ—¶é—´ï¼ˆç§’ï¼‰
    read-timeout: 10
  pay:
    order-notify-url: https://yutou.mynatapp.cc/admin-api/pay/notify/order # æ”¯ä»˜æ¸ é“çš„ã€æ”¯ä»˜ã€‘å›è°ƒåœ°å€
    refund-notify-url: https://yutou.mynatapp.cc/admin-api/pay/notify/refund # æ”¯ä»˜æ¸ é“çš„ã€é€€æ¬¾ã€‘å›è°ƒåœ°å€
    transfer-notify-url: https://yutou.mynatapp.cc/admin-api/pay/notify/transfer # æ”¯ä»˜æ¸ é“çš„ã€è½¬è´¦ã€‘å›è°ƒåœ°å€
  access-log: # è®¿é—®æ—¥å¿—çš„é…ç½®é¡¹
    enable: false
  demo: false # å…³é—­æ¼”ç¤ºæ¨¡å¼
  wxa-code:
    env-version: develop # å°ç¨‹åºç‰ˆæœ¬: æ­£å¼ç‰ˆä¸º "release"ï¼›ä½“éªŒç‰ˆä¸º "trial"ï¼›å¼€å‘ç‰ˆä¸º "develop"
  wxa-subscribe-message:
    miniprogram-state: developer # è·³è½¬å°ç¨‹åºç±»å‹ï¼šå¼€å‘ç‰ˆä¸º â€œdeveloperâ€ï¼›ä½“éªŒç‰ˆä¸º â€œtrialâ€ä¸ºï¼›æ­£å¼ç‰ˆä¸º â€œformalâ€
  tencent-lbs-key: TVDBZ-TDILD-4ON4B-PFDZA-RNLKH-VVF6E # QQ åœ°å›¾çš„å¯†é’¥ https://lbs.qq.com/service/staticV2/staticGuide/staticDoc

justauth:
  enabled: true
  type:
    DINGTALK: # é’‰é’‰
      client-id: dingvrnreaje3yqvzhxg
      client-secret: i8E6iZyDvZj51JIb0tYsYfVQYOks9Cq1lgryEjFRqC79P3iJcrxEwT6Qk2QvLrLI
      ignore-check-redirect-uri: true
    WECHAT_ENTERPRISE: # ä¼ä¸šå¾®ä¿¡
      client-id: wwd411c69a39ad2e54
      client-secret: 1wTb7hYxnpT2TUbIeHGXGo7T0odav1ic10mLdyyATOw
      agent-id: 1000004
      ignore-check-redirect-uri: true
    # noinspection SpringBootApplicationYaml
    WECHAT_MINI_PROGRAM: # å¾®ä¿¡å°ç¨‹åº
      client-id: ${wx.miniapp.appid}
      client-secret: ${wx.miniapp.secret}
      ignore-check-redirect-uri: true
      ignore-check-state: true # å¾®ä¿¡å°ç¨‹åºï¼Œä¸ä¼šä½¿ç”¨åˆ° stateï¼Œæ‰€ä»¥ä¸è¿›è¡Œæ ¡éªŒ
    WECHAT_MP: # å¾®ä¿¡å…¬ä¼—å·
      client-id: ${wx.mp.app-id}
      client-secret: ${wx.mp.secret}
      ignore-check-redirect-uri: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # ç¼“å­˜å‰ç¼€ï¼Œç›®å‰åªå¯¹ Redis ç¼“å­˜ç”Ÿæ•ˆï¼Œé»˜è®¤ JUSTAUTH::STATE::
    timeout: 24h # è¶…æ—¶æ—¶é•¿ï¼Œç›®å‰åªå¯¹ Redis ç¼“å­˜ç”Ÿæ•ˆï¼Œé»˜è®¤ 3 åˆ†é’Ÿ

--- #################### iotç›¸å…³é…ç½® TODO èŠ‹è‰¿ã€IOTã€‘ï¼šå†ç…ç… ####################
pf4j:
#  pluginsDir: /tmp/
  pluginsDir: ../plugins